DROP DATABASE IF EXISTS chirpy;
CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE chirps(
id Int AUTO_INCREMENT NOT NULL, 
author VARCHAR(225) NOT NULL, 
body VARCHAR (225) NOT NULL, 
created_at DATETIME NOT NULL,

PRIMARY KEY(id));

select * from chirps
